Hotfix/fix styles bugs on game styles form
Quest-Finder/temvagamestre.frontend pull request #105
Opened 2024-07-10 02:23 UTC by viniciusmontibeller

# Tipo 
* [x] Bug fix: correção de um problema
* [] New feature (ready): adição de nova funcionalidade pronta para publicação
* [] New feature (partial): adição de nova funcionalidade, porém incompleta
* [] Refactor: refatoração de código 
* [] Chore: alteração de documentação, pacotes ou testes, sem afetar o usuário final
* [] Release: nova versão da aplicação - somente para produção
* [] Other: especifique caso nenhuma opção acima se adeque

## Descrição
Ajustado bugs de estilo que constavam nas duas últimas partes do formulário, como no array de checkbox para selecionar os estios de jogo, fonte.
Ajustado erro de importação do arquivo json que prove os testos estáticos para o formulário

## Screenshots / Imagens / Vídeos
* N/A

## Tarefas ou Issue
* N/A

## Checklist
* [x] Eu revisei meu código
* [x] As alterações passam pelos testes e lint locais
* [] Eu comentei em partes de maior complexidade para melhorar a compreensão (se aplicável)
* [] Eu criei testes para minha correção ou funcionalidade (se aplicável):
    * [] Testes unitários
    * [] Testes de integração

## Instruções para teste

## Dependências
* Esses bugs dependen dos ultimos PR's mergeados, referentes a Estilos de jogo, e Peril do jogador. Neles foi adicionado a variavel de ambiente NEXT_PUBLIC_BASE_URL com a url base da api.

2024-07-10 11:59 UTC, MathMendesReis approved these changes

2024-08-08 01:55 UTC, emerson-oliveira commented
@viniciusmontibeller , padronize o nome das pastas deixando separados por - exemplo de `social network registration` para `social-network-registration`, espaço ou caracteres especiais em nome de pastas ou arquivos pode quebrar o build.

2024-08-08 02:00 UTC, emerson-oliveira requested changes

2024-08-08 02:00 UTC, emerson-oliveira commented on src/features/register-player/player-registration/FormStepOne.tsx
>  import useSubmitStepOne from './hooks/useSubmitStepOne'
vc pode criar um arquivo `./hook/index.ts` que vai receber ser responsavel pela exportação, e nessa parte vc faria a importação da seguinte forma.
`import { useFormStepOne, useSubmitStepOne } from './hooks'`

2024-08-10 00:58 UTC, viniciusmontibeller commented on src/features/register-player/player-registration/FormStepOne.tsx
>  import useSubmitStepOne from './hooks/useSubmitStepOne'
Tentei alterar em outros lugares também, mas em alguns deles dava erro de dependência cíclica, aí tive que dosar um pouco.

2024-08-10 14:57 UTC, emerson-oliveira approved these changes

2024-08-10 14:58 UTC, merged