Refactor/form address registration
Quest-Finder/temvagamestre.frontend pull request #111
Opened 2024-07-11 20:29 UTC by MathMendesReis

# Tipo 
* [ ] Bug fix: correção de um problema
* [ ] New feature (ready): adição de nova funcionalidade pronta para publicação
* [ ] New feature (partial): adição de nova funcionalidade, porém incompleta
* [x] Refactor: refatoração de código 
* [ ] Chore: alteração de documentação, pacotes ou testes, sem afetar o usuário final
* [ ] Release: nova versão da aplicação - somente para produção
* [ ] Other: especifique caso nenhuma opção acima se adeque

## Descrição
 - Correção de estilo
 - Desabilitar button caso o form esteja invalido
 - alteração de logica, como o Juliano recomendou, foi invertida a logica do live in brazil, passando a utlizar o live abroad, facilitando leitura do codigo

## Checklist
* [x] Eu revisei meu código
* [x] As alterações passam pelos testes e lint locais
* [ ] Eu comentei em partes de maior complexidade para melhorar a compreensão (se aplicável)
* [ ] Eu criei testes para minha correção ou funcionalidade (se aplicável):
    * [ ] Testes unitários
    * [ ] Testes de integração

2024-07-11 20:52 UTC, julianosill commented on src/features/register-player/address registration/components/ checkbox-live-abroad.tsx
> +                id='liveInBrazil'
Altera o id para `liveAbroad` pra não confundir na leitura.

2024-07-11 20:56 UTC, julianosill commented on src/features/register-player/address registration/components/options-city.tsx
> +    <ul className='m z-1 h-[40px]  w-full max-w-[320px] overflow-hidden rounded-md  border border-gray-200 bg-white'>
Aqui não seria um `<li>`?

2024-07-11 20:56 UTC, julianosill commented on src/features/register-player/address registration/components/options-city.tsx
>            <ul
Aqui não seria um `<li>`?

2024-07-12 01:15 UTC, julianosill commented on src/features/register-player/address registration/components/options-city.tsx
> +    <ul className='m z-1 h-[40px]  w-full max-w-[320px] overflow-hidden rounded-md  border border-gray-200 bg-white'>
Tem um `m ` perdido no início da classe e também alguns espaços extras.

2024-07-12 01:16 UTC, julianosill commented on src/features/register-player/address registration/components/options-city.tsx
> +              </p>
Não entendi porque inserir uma tag `<p>` dentro de `<button>`.

Não seria melhor aplicar os estilos direto no botão e inserir o conteúdo direto dele?

2024-07-12 01:49 UTC, viniciusmontibeller approved these changes

2024-07-12 21:57 UTC, MathMendesReis commented on src/features/register-player/address registration/components/options-city.tsx
> +              </p>
pode ser, vou refazer.

2024-07-13 01:59 UTC, julianosill approved these changes
Precisa só resolver os erros do Codacy e aí pode passar para Code Review.

2024-08-01 03:19 UTC, emerson-oliveira commented
@MathMendesReis , se vc clicar no link fornecido pelo sonar [1 New issue](https://sonarcloud.io/project/issues?id=Quest-Finder_temvagamestre.frontend&pullRequest=111&issueStatuses=OPEN,CONFIRMED&sinceLeakPeriod=true), vc vai visualizar uma tarefa sugerida para correção.

É bem simples de corrigir, mas aproveite para entender como o sonar pode te ajudar a melhorar a qualidade do código.

Na aba **Why is this an issue?** :
Você vai encontra mais informações de como resolver esse erro.
![image](https://github.com/user-attachments/assets/75c9d12f-8ed6-42ca-ab9a-2ae40f84f910)

2024-08-02 01:29 UTC, MathMendesReis commented
A tela ficou assim
![Captura de tela de 2024-08-01 22-20-58](https://github.com/user-attachments/assets/56c0df16-22cc-4f16-b886-90d5161d3323)


Obs: A respeito do Botão de 'Prefiro responder em outro momento', esse erro ta sendo resolvido em outro PR, pois acaba envolvendo outros formulários

2024-08-10 14:55 UTC, emerson-oliveira reviewed
@MathMendesReis , resolve os conflitos para liberar o PR

2024-08-26 15:15 UTC, emerson-oliveira requested changes
Além das correções mencionadas, também pode ser aplicado a troca do nome dos arquivos de `camelCase` para `kebab case`

2024-08-26 15:15 UTC, emerson-oliveira commented on src/features/register-player/address-registration/components/checkbox-live-abroad.tsx
>                  title='Não moro no Brasi'
transferir o texto para o locale

2024-08-26 15:15 UTC, emerson-oliveira commented on src/features/register-player/address-registration/components/checkbox-live-abroad.tsx
>              <FormLabel>Não moro no Brasil</FormLabel>
Transferir o texto para o locale

2024-08-26 15:15 UTC, emerson-oliveira commented on src/features/register-player/address-registration/utils/address-registration-validation.ts
> +        "Se 'liveAbroad' for verdadeiro, 'state' e 'city' devem estar vazios. Se 'liveAbroad' for falso, 'state' e 'city' devem estar preenchidos.",
transferir mensagem para o locale

2024-08-26 15:15 UTC, emerson-oliveira commented on src/features/register-player/social-network-registration/utils/get-icon-by-name.ts
>  export function getIconByName(socialMedia: string) {
Podemos utilizar um objeto de mapeamento ao invés de um `switch` para simplificar e tornar o código mais limpo e fácil de manter

2024-08-26 18:53 UTC, emerson-oliveira approved these changes

2024-08-26 18:54 UTC, merged