Fix/clerk
Quest-Finder/temvagamestre.frontend pull request #112
Opened 2024-07-12 23:00 UTC by MathMendesReis

- Tem o objetivo de corrigir o bug do clerk, alguns métodos estavam depreciados, então atualizei as dependências e refatorei o middleware

2024-08-02 17:07 UTC, emerson-oliveira approved these changes

2024-08-06 01:29 UTC, viniciusmontibeller approved these changes

2024-08-10 14:53 UTC, emerson-oliveira reviewed
@MathMendesReis , tenta resolver os conflitos dos arquivos e liberar o PR pra gente

2024-08-24 01:35 UTC, emerson-oliveira requested changes

2024-08-24 01:35 UTC, emerson-oliveira commented on package.json
> +    "@clerk/nextjs": "^5.3.3",
Remover o `^` da dependencia.

2024-08-24 01:35 UTC, emerson-oliveira commented on package.json
> +    "@clerk/localizations": "^2.6.1",
Remover o `^` da dependencia.

2024-08-24 02:42 UTC, emerson-oliveira approved these changes

2024-08-24 02:42 UTC, merged