[TEMVAGA-315] Tela de cadastro de usuário
Quest-Finder/temvagamestre.frontend pull request #135
Opened 2024-08-11 01:29 UTC by julianosill

## Tipo

- [ ] Bug fix: correção de um problema
- [ ] New feature (ready): adição de nova funcionalidade pronta para publicação
- [x] New feature (incomplete): adição de nova funcionalidade, porém incompleta
- [ ] Refactor: refatoração de código
- [ ] Chore: alteração de documentação, pacotes ou testes, sem afetar o usuário final
- [ ] Release: nova versão da aplicação - somente para produção
- [ ] Other: especifique caso nenhuma opção acima se adeque

## Descrição

Esta Pull Request adiciona a tela de cadastro do usuário e também algumas funcionalidades, como:
- Criação de temas (claro e escuro) com tokens globais de cor;
- Seletor de tema adicionado no canto inferior esquerdo de forma provisória até que essa funcionalidade seja definida e criada por POs e designers;
- Atualização do componente `input` adicionando variantes de status (info, aviso, erro, sucesso) e ícone (padrão ou passado como propriedade).

### Observações
- A estrutura já está seguindo a documentação de estudo apresentado;
- A função de cadastro de usuário será atualizada quando o `endpoint` for disponibilizado. Será adicionado um `toast` após o sucesso do cadastro e, em seguida, o usuário será direcionado à página de login;
- Foram criados alguns componentes com o sufixo `-new.tsx` para evitar que o restante da aplicação quebre até que a migração de todos os componentes para o novo style guide seja concluída. Após a migração, estes componentes serão apontados como principais;
- O `Clerk` foi removido até decidirmos qual será a estratégia para autenticação e validação dos usuários;
- Os formulários de cadastro de perfil do jogador sofrerão alterações devido a mudanças de estilo em alguns componentes. Isso é esperado, pois essas telas estão com design desafado e serão atualizadas mais à frente.
 
# Screenshots / Imagens / Videos

https://github.com/user-attachments/assets/847f51ca-20d8-46cd-83aa-b0494cae645e

https://github.com/user-attachments/assets/5bd4f2b7-f45e-45e8-a896-cab2de109728

![image](https://github.com/user-attachments/assets/a809e838-bbdd-45c4-b3ef-bdd2796ecb0b)

## Tarefas ou Issue

- #130 

## Checklist

- [x] Eu revisei meu código
- [x] As alterações passam pelos testes e lint locais
- [x] Eu comentei em partes de maior complexidade para melhorar a compreensão (se aplicável)
- [ ] Eu criei testes para minha correção ou funcionalidade (se aplicável):
  - [ ] Testes unitários
  - [ ] Testes de integração

## Instruções para teste

- Insira o e-mail `sucesso@teste.com` para simular o sucesso do cadastro;
- Qualquer outro e-mail irá resultar no erro de e-mail já cadastrado.

## Dependências

Depende do `endpoint` para cadastrar usuário, referente a essa issue [aqui](https://github.com/Quest-Finder/temvagamestre.server/issues/71).

2024-08-12 22:03 UTC, viniciusmontibeller commented on src/app/auth/sign-up/_components/sign-up-form.tsx
> +import { ShowAndHideButton } from '../../../../components/ui/show-and-hide-button'
Aqui poderia ser usado o alias de importação como

`@/components/ui/show-and-hide-button`

2024-08-12 22:03 UTC, viniciusmontibeller commented on src/app/auth/sign-up/_helpers/sign-up-form-validation.ts
> +const t = texts.SignUpForm
Aqui poderia ter um nome mais semântico de acordo com a variável, apesar de ficar maior, facilita leitura e entendimento.

Ex:
`const signUpFormTexts = texts.SignUpForm`

2024-08-12 22:03 UTC, viniciusmontibeller commented on src/components/ui/dropdown-menu.tsx
> +        'z-50 min-w-28 overflow-hidden rounded-md border border-border bg-background-soft p-1 text-foreground shadow-md data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed
Aqui, como em um outro PR meu ja foi sugerido, poderia separar as classes pela função, no caso, baseClasses, stateClasses, e outras caso existam.

2024-08-12 22:03 UTC, viniciusmontibeller commented on src/app/auth/sign-up/_helpers/get-password-status.ts
Aqui não seria melhor tirar a tipagem para um arquivo em separado?

2024-08-12 22:03 UTC, viniciusmontibeller commented on src/app/auth/sign-up/_components/sign-up-form.tsx
Aqui poderia ser extraído a lógica do componente separando a responsabilidade apenas como renderização.

2024-08-13 00:37 UTC, julianosill commented on src/app/auth/sign-up/_components/sign-up-form.tsx
> +import { ShowAndHideButton } from '../../../../components/ui/show-and-hide-button'
Opa, a importação automática puxou isso e nem reparei, valeu por notar!

2024-08-13 00:48 UTC, julianosill commented on src/app/auth/sign-up/_helpers/get-password-status.ts
Eu sigo a regra de que, se a tipagem for utilizada exclusivamente em um arquivo ou local, não há necessidade de criar um novo arquivo só para importar/exportar esta tipagem.

Quando essa tipagem passar a ser utilizada ou importada em mais locais, aí sim centralizamos em um arquivo e importamos onde for necessário.

Neste caso, ambas as tipagens `GetPasswordStatusProps` e `PasswordStatus` só são utilizadas neste arquivo. Assim evitamos a criação de muitos arquivos sem necessidade.

O que você acha?

2024-08-13 00:51 UTC, julianosill commented on src/app/auth/sign-up/_helpers/sign-up-form-validation.ts
> +const t = texts.SignUpForm
Eu segui a mesma linha desta biblioteca de internacionalização para o Next: https://github.com/amannn/next-intl

Achei uma abordagem bem prática e mantive o mesmo formato já pensando em uma possível implementação de outros idiomas. Assim já mantém a base de código mais próxima essa implementação posterior.

Mas se acha que a leitura ficou ruim, vou fazer esses ajustes nos arquivos necessários.

2024-08-13 00:54 UTC, julianosill commented on src/components/ui/dropdown-menu.tsx
> +        'z-50 min-w-28 overflow-hidden rounded-md border border-border bg-background-soft p-1 text-foreground shadow-md data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed
Sim, concordo. Esse componente está em segundo plano, inclusive marquei o `TODO:` ali para implementar isso mais adiante.

Por hora, esse componente não é utilizado oficialmente, apenas adicionei para poder incluir o seletor de temas temporário.

Irei fazer a implementação do novo style guide, já com os ajustes de classes na próxima etapa.

2024-08-13 21:33 UTC, viniciusmontibeller commented on src/components/ui/dropdown-menu.tsx
> +        'z-50 min-w-28 overflow-hidden rounded-md border border-border bg-background-soft p-1 text-foreground shadow-md data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed
Ahh sim tranquilo. Qualquer coisa dá pra deixar sinalizado, caso alguém for utilizar ou mexer nele, já poderia fazer essa alteração, aí também não fugiria muito da finalidade da tarefa em questão

2024-08-13 21:38 UTC, viniciusmontibeller commented on src/app/auth/sign-up/_helpers/sign-up-form-validation.ts
> +const t = texts.SignUpForm
A preocupação maior seria para pessoas novas ou que forem entrar futuramente, como não temos nada em específico definido sobre, normalmente opta por ter algo bem descritivo. Caso a gente use esse padrão, para facilitar outros idiomas futuramente, nesse caso podemos ter algo documentado.

Aqui estamos só vendo sugestões de nomenclatura. Acho muito válido o teu ponto de abrir pros outros idiomas no futuro.

2024-08-13 21:41 UTC, viniciusmontibeller commented on src/app/auth/sign-up/_helpers/get-password-status.ts
Ah claro, tens razão concordo contigo. Nesse caso estava pensando em separação de responsabilidades, onde iriamos separar os arquivos com suas ações especificas, para se ter uma melhor manutenção, mas nesse caso não teria necessidade.

2024-08-13 21:42 UTC, viniciusmontibeller approved these changes

2024-08-13 22:10 UTC, julianosill commented on src/app/auth/sign-up/_helpers/sign-up-form-validation.ts
> +const t = texts.SignUpForm
Bom ponto! Reavaliamos isso quando houver uma implementação de idiomas. E mantemos as variáveis mais descritivas por hora.

2024-08-13 22:13 UTC, julianosill commented on src/components/ui/dropdown-menu.tsx
> +        'z-50 min-w-28 overflow-hidden rounded-md border border-border bg-background-soft p-1 text-foreground shadow-md data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed
Sim, inclusive já estou fazendo isso para adiantar a organização do componente. Subi antes para agilizar a tarefa e podermos avançar na sprint.

2024-08-17 16:16 UTC, emerson-oliveira requested changes

2024-08-17 16:16 UTC, emerson-oliveira commented on src/app/auth/sign-up/_helpers/get-password-status.ts
> +  switch (errorType) {
Você pode refatorar esse código usando um objeto de mapeamento em vez de um `switch` para tornar o código mais conciso e fácil de manter:

```
const errorMessages: Record<string, string | undefined> = {
  too_small: 'error',
  invalid_string: 'warning',
};

const result = errorMessages[errorType] ?? undefined;

```

2024-08-17 16:16 UTC, emerson-oliveira commented on src/app/auth/sign-up/_hooks/use-sign-up-form.ts
> +  function handleRegister(data: FormSchema) {
Sinto falta da desestruturação da assinatura da função e tipagem do retorno

2024-08-17 16:16 UTC, emerson-oliveira commented on src/components/form/use-form-field.ts
> +  const fieldContext = React.useContext(FormFieldContext)
Adicionar a tipagem do contexto

2024-08-17 16:16 UTC, emerson-oliveira commented on src/components/form/use-form-field.ts
> +  const itemContext = React.useContext(FormItemContext)
Adicionar a tipagem do contexto

2024-08-17 16:16 UTC, emerson-oliveira commented on src/components/form/use-form-field.ts
> +    name: fieldContext.name,
Assim como foi feito com `id` esse item poderia ser desestruturado

2024-08-17 16:16 UTC, emerson-oliveira commented on src/components/theme-toggle.tsx
> +          Claro
Esses itens podem ser movidos para o locales

2024-08-17 16:16 UTC, emerson-oliveira commented on src/components/theme-toggle.tsx
> +          Escuro
Esses itens podem ser movidos para o locales

2024-08-17 16:16 UTC, emerson-oliveira commented on src/components/theme-toggle.tsx
> +          Sistema
Esses itens podem ser movidos para o locales

2024-08-18 16:26 UTC, emerson-oliveira approved these changes

2024-08-18 16:26 UTC, merged