feature/player-onboarding
Quest-Finder/temvagamestre.frontend pull request #136
Opened 2024-08-15 14:01 UTC by julianosill

## Tipo

- [ ] Bug fix: correção de um problema
- [x] New feature (ready): adição de nova funcionalidade pronta para publicação
- [ ] New feature (incomplete): adição de nova funcionalidade, porém incompleta
- [ ] Refactor: refatoração de código
- [ ] Chore: alteração de documentação, pacotes ou testes, sem afetar o usuário final
- [ ] Release: nova versão da aplicação - somente para produção
- [ ] Other: especifique caso nenhuma opção acima se adeque

## Descrição

Criação da tela de _onboarding_, para onde o usuário será direcionado após seu primeiro login. Alguns ajustes de design foram feitos e repassados aos POs e designers no Figma (comentado no card da tarefa do ClickUp).

Também foi criado, como componente global, um botão para navegação interna da aplicação utilizando as propriedades do `next/link`

### Observações

- O arquivo `/constants/routes.ts` será responsável por armazenar as rotas da aplicação, seguindo a nova proposta de arquitetura de pastas/arquivos.
- Na próxima sprint, precisaremos revisar a organização dessas rotas, como padrão de nomenclaturas e agrupamentos. Por hora, apenas adicionei a tela de onboarding em `services/routers.ts` para torná-la temporariamente pública e não ser barrada pelo Clerk.

## Screenshots / Imagens / Videos

![screens](https://github.com/user-attachments/assets/bdaef5e3-b120-44e4-a7ef-81072edf5301)

## Tarefas ou Issue

- #131 
- Tarefa no [ClickUp](https://app.clickup.com/t/9013198100/TEMVAGA-309)

## Checklist

- [x] Eu revisei meu código
- [x] As alterações passam pelos testes e lint locais
- [ ] Eu comentei em partes de maior complexidade para melhorar a compreensão (se aplicável)
- [ ] Eu criei testes para minha correção ou funcionalidade (se aplicável):
  - [ ] Testes unitários
  - [ ] Testes de integração

## Instruções para teste

N/A

## Dependências

Depende do merge de #135 ([TEMVAGA-315] Tela de cadastro de usuário), que deve ser realizado primeiro.

2024-08-15 23:10 UTC, viniciusmontibeller approved these changes

2024-08-17 16:02 UTC, emerson-oliveira requested changes

2024-08-17 16:02 UTC, emerson-oliveira commented on src/app/auth/sign-up/assets/sign-up-image.jpg
Esse arquivo poderia estar na pasta `./src/assets/` o mesmo para todas as imagens presentes nessa pasta

2024-08-17 16:02 UTC, emerson-oliveira commented on src/app/auth/sign-up/_hooks/use-sign-up-form.ts
> +  function handleRegister(data: FormSchema) {
desestruturar o data na assinatura é considerado uma boa prática

2024-08-17 16:02 UTC, emerson-oliveira commented on src/app/auth/sign-up/_hooks/use-sign-up-form.ts
> +import { getPasswordStatus } from '../_helpers/get-password-status'
crie um arquivo `index.ts` dentro do `_helpers` e faça a exportação dos arquivos e aqui faça algo como 
```
import { getPasswordStatus, defaultValues,  type FormSchema, formSchema, } from '../_helpers
```

2024-08-17 16:02 UTC, emerson-oliveira commented on src/app/icon.png
Acredito que o local certo desse item é na pasta `./src/assets/`

2024-08-17 16:02 UTC, emerson-oliveira commented on src/app/register/onboarding/assets/bg-image.jpg
Acredito que o local certo desse item é na pasta `./src/assets/`

2024-08-17 16:59 UTC, julianosill commented on src/app/auth/sign-up/assets/sign-up-image.jpg
Essa imagem é utilizada apenas na página de cadastro. Nós vamos centralizar todas as imagens no assets global então?

2024-08-17 17:01 UTC, julianosill commented on src/app/auth/sign-up/_hooks/use-sign-up-form.ts
> +  function handleRegister(data: FormSchema) {
Sim, já iria seguir a desestruturação. Essa função foi criada apenas para ter o exemplo até realizar a integração da API.

Mas já vou atualizar para ter isso encaminhado quando for integrar.

2024-08-17 17:21 UTC, julianosill commented on src/app/icon.png
A documentação do Next ([neste link](https://nextjs.org/docs/app/api-reference/file-conventions/metadata/app-icons)) informa que o arquivo do favicon deve estar neste local.

```
Use an image file to set an app icon by placing a favicon, icon, or apple-icon image file within your /app directory. The favicon image can only be located in the top level of app/.
```

2024-08-18 01:39 UTC, emerson-oliveira commented on src/app/auth/sign-up/assets/sign-up-image.jpg
Vamos centralizar os arquivos estáticos nessa página.

2024-08-18 01:40 UTC, emerson-oliveira commented on src/app/icon.png
Ótimo ponto é uma peculiaridade do next, nesse caso vamos manter nessa pasta mesmo.

2024-08-19 15:35 UTC, emerson-oliveira approved these changes

2024-08-19 15:35 UTC, merged