feature/login-page
Quest-Finder/temvagamestre.frontend pull request #149
Opened 2024-09-11 02:42 UTC by julianosill

## Tipo

- [ ] Bug fix: correção de um problema
- [ ] New feature (ready): adição de nova funcionalidade pronta para publicação
- [x] New feature (incomplete): adição de nova funcionalidade, porém incompleta
- [ ] Refactor: refatoração de código
- [ ] Chore: alteração de documentação, pacotes ou testes, sem afetar o usuário final
- [ ] Release: nova versão da aplicação - somente para produção
- [ ] Other: especifique caso nenhuma opção acima se adeque

## Descrição

Criação da página de autenticação do usuário, utilizando e-mail/senha ou rede social.

### Observações

- As funções de autenticação, criação de sessão e afins serão atualizadas quando os *endpoints* da API estiverem disponíveis;
- O *cookie* de sessão está definido com expiração de 24h temporariamente. Precisamos ajustar isso quando definirmos a regra de validação dos *token* e *refreshToken*.

## Screenshots / Imagens / Videos

![sign-in-page](https://github.com/user-attachments/assets/6e7ec943-c749-4f00-ab66-30a1d3dce2da)

## Tarefas ou Issue

- N/A

## Checklist

- [x] Eu revisei meu código
- [x] As alterações passam pelos testes e lint locais
- [x] Eu comentei em partes de maior complexidade para melhorar a compreensão (se aplicável)
- [ ] Eu criei testes para minha correção ou funcionalidade (se aplicável):
  - [ ] Testes unitários
  - [ ] Testes de integração

## Instruções para teste

- Acesso com e-mail `sucesso@teste.com` e senha `123` irá direcionar para a tela de *dashboard* (ainda não existe);
- Acesso com e-mail `onboarding@teste.com` e senha `123` irá direcionar para a tela de *onboarding*;
- Acesso por rede social irá direcionar para *dashboard*.

## Dependências

É necessário adicionar a variável de ambiente com o valor abaixo:
```
NEXT_PUBLIC_CLERK_SIGN_IN_URL="/auth/sign-in"
```

2024-09-11 22:53 UTC, emerson-oliveira requested changes

2024-09-11 22:53 UTC, emerson-oliveira commented on src/constants/routes.ts
Nesse cenário nosso acredito que seria melhor agrupar todos os paths em um objeto só

No projeto que trabalho usamos o `@/paths.ts`  onde temos um objeto com todos os paths do sistema facilita a manutenção depois
Exemplo: 
```
export const paths = {
  home: '/',
  auth: {
    custom: {
      signIn: '/',
      signUp: '/sign-up',
      resetPassword: '/reset-password'
    }
  },
  dashboard: {
    overview: '/admin',
    settings: {
      security: '/dashboard/settings/security',
    },
    users: {
      list: '/dashboard/users',
      create: '/dashboard/users/create',
      details: (userId: string) => `/dashboard/users/${userId}`,
    },
  },
}
```

2024-09-11 22:53 UTC, emerson-oliveira commented on src/components/sign-out-button.tsx
> +      sign-out
Adicionar tradução

2024-09-11 22:53 UTC, emerson-oliveira commented on src/app/(home)/page.tsx
> +          onboarding
Adicionar tradução

2024-09-11 22:53 UTC, emerson-oliveira commented on src/app/(home)/page.tsx
> +          register player profile
Adicionar tradução

2024-09-11 22:53 UTC, emerson-oliveira commented on src/app/(home)/page.tsx
> +        <NavButton href={AUTH_ROUTES.SIGN_UP}>sign-up</NavButton>
Adicionar tradução

2024-09-11 22:53 UTC, emerson-oliveira commented on src/app/(home)/page.tsx
> +        <NavButton href={AUTH_ROUTES.SIGN_IN}>sign-in</NavButton>
Adicionar tradução

2024-09-12 01:22 UTC, julianosill commented on src/constants/routes.ts
Concordo, acho interessante essa abordagem. Estava seguindo o padrão anterior e ajustando, mas acredito que sua proposta seja a melhor opção.

Vou atualizar o arquivo subir as alterações.

2024-09-12 01:25 UTC, julianosill commented on src/components/sign-out-button.tsx
> +      sign-out
Este e os demais botões citados foram inseridos na página inicial apenas para podermos acessar as respectivas telas de forma mais prática no momento. Eles serão removidos quando tivermos a landing page e conforme formos criando as demais telas, tendo um fluxo melhor para testar as rotas.

2024-09-16 14:40 UTC, emerson-oliveira approved these changes

2024-09-16 14:40 UTC, merged